<a href="https://colab.research.google.com/github/habibur-rahman-swe/MedicalImageProcessing/blob/udemy/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# 2. NumPy Arrays
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
arr = np.array(mylist)

In [7]:
arr

array([1, 2, 3])

In [8]:
mylist = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
mymatrix = np.array(mylist)

In [10]:
mymatrix.shape

(3, 3)

In [11]:
mynewmatrix = np.array(mylist)
mynewmatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
type(0.0)

float

In [15]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((5, 5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [17]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(5, 5)

array([[0.91237352, 0.43361205, 0.79908757, 0.35671082, 0.43783452],
       [0.16857385, 0.4303511 , 0.5166495 , 0.3376785 , 0.56179244],
       [0.16883791, 0.66553667, 0.2696243 , 0.60927957, 0.35110915],
       [0.42952284, 0.42958351, 0.35852097, 0.41772851, 0.40768482],
       [0.13173358, 0.5151142 , 0.71563754, 0.48154164, 0.8581712 ]])

In [24]:
np.random.randn(1)

array([-0.20768165])

In [25]:
np.random.normal

<function RandomState.normal>

In [27]:
np.random.randint(5, 100, 10)

array([51, 66, 40, 17, 15, 84, 51, 26, 43, 81])

In [31]:
np.random.seed(52)
np.random.rand(5)

array([0.82311034, 0.02611798, 0.21077064, 0.61842177, 0.09828447])

In [32]:
np.random.rand(5)

array([0.62013131, 0.05389022, 0.96065406, 0.98042937, 0.52112765])

In [34]:
arr = np.arange(35)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [36]:
ranarr = np.random.randint(0, 50, 10)

In [37]:
ranarr

array([49, 16, 11, 48, 46, 42, 45, 15, 12, 39])

In [39]:
arr.reshape(5, 7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [40]:
ranarr

array([49, 16, 11, 48, 46, 42, 45, 15, 12, 39])

In [41]:
ranarr.max()

49

In [42]:
ranarr.min()

11

In [43]:
ranarr.argmax()

0

In [44]:
ranarr.argmin()

2

In [45]:
ranarr.dtype

dtype('int64')

In [46]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[8] = 8
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[1 : 5]

array([1, 2, 3, 4])

In [49]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [50]:
arr[:5]

array([0, 1, 2, 3, 4])

In [51]:
arr[5:
]

array([ 5,  6,  7,  8,  9, 10])

In [52]:
arr[:-5]

array([0, 1, 2, 3, 4, 5])

In [53]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [54]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [55]:
new_arr = arr * 5
new_arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [56]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
slice_of_arr = arr[0:6]

In [59]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [60]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [61]:
slice_of_arr[:] = 99

In [62]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [63]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [67]:
arr_copy[:] = 1000

In [68]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [69]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [25, 40, 45]])

In [70]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [25, 40, 45]])

In [71]:
arr_2d.shape

(3, 3)

In [72]:
arr_2d[1]

array([20, 25, 30])

In [73]:
arr_2d[1][2]

30

In [74]:
arr_2d[1, 1]

25

In [75]:
arr_2d[2,2]

45

In [76]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [77]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [78]:
arr = np.arange(1, 11)

In [79]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [81]:
bool_arr = arr > 4

In [82]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [84]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [85]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [86]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [87]:
arr[arr == 2]

array([2])

In [88]:
arr[arr <= 6]

array([1, 2, 3, 4, 5, 6])

In [89]:
arr = np.arange(0, 10)

In [90]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [92]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [93]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [94]:
(arr + 2) / 100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [95]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [96]:
1 / arr

<ipython-input-96-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [97]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [98]:
np.log(arr)

<ipython-input-98-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [99]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [100]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [101]:
arr.sum()

45

In [102]:
arr.mean()

4.5

In [103]:
arr.max()

9

In [104]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [105]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [106]:
arr_2d.shape

(3, 4)

In [107]:
arr_2d.sum()

78

In [108]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [109]:
arr_2d.sum(axis=1)

array([10, 26, 42])

In [110]:
arr_2d.sum(axis=1)

array([10, 26, 42])

In [111]:
import numpy as np

In [112]:
arr = np.zeros(10)

In [113]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [114]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [115]:
arr = np.ones(10) * 5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [116]:
arr = np.arange(10, 51)

In [117]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [118]:
arr = np.arange(10, 50, 2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [120]:
arr = np.arange(9)
arr.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [121]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [122]:
np.random.rand(1)

array([0.68192648])

In [123]:
arr = np.random.randn(25)
arr

array([ 0.97307206, -0.35664161, -0.78829462, -0.23257772, -0.84750125,
       -1.74825258,  0.80807157,  1.23979542,  0.56063586, -0.54281703,
       -0.48414947,  1.31982782,  1.44554   ,  0.05181732,  1.62867942,
       -0.36600024, -0.02424209, -0.82656541, -1.55539836, -0.4018704 ,
       -0.60889302, -0.06615728,  1.1521841 , -0.00729803,  0.69459216])

In [124]:
np.arange(1, 101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [125]:
arr = np.arange(1, 101) / 100

In [126]:
arr.reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [127]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [128]:
mat = np.arange(1, 26).reshape(5, 5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [130]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [131]:
mat[3, 4]

20

In [132]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [133]:
mat[4, :]

array([21, 22, 23, 24, 25])

In [134]:
mat[3:5, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [135]:
mat.sum()

325

In [136]:
mat.std()

7.211102550927978

In [137]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [138]:
np.random.seed(101)

In [140]:
np.random.rand(1)

array([0.57066759])