<a href="https://colab.research.google.com/github/habibur-rahman-swe/MedicalImageProcessing/blob/udemy/Tensor_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import torch

In [37]:
import numpy as np

In [38]:
torch.__version__

'2.2.1+cu121'

In [39]:
arr = np.array([1, 2, 3, 4, 5])

In [40]:
arr.dtype

dtype('int64')

In [41]:
type(arr)

numpy.ndarray

In [42]:
x = torch.from_numpy(arr)

In [43]:
type(x)

torch.Tensor

In [44]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [45]:
x

tensor([1, 2, 3, 4, 5])

In [46]:
x.dtype

torch.int64

In [47]:
arr2d = np.arange(0.0, 12.0)

In [48]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [49]:
arr2d = arr2d.reshape(4, 3)

In [50]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [51]:
arr2d.reshape(4, 3)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [52]:
arr[0]

1

In [53]:
arr = arr2d

In [54]:
arr[1]

array([3., 4., 5.])

In [55]:
arr[0] * arr[1]

array([ 0.,  4., 10.])

In [56]:
my_arr = np.arange(0, 10)

In [57]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
my_tensor = torch.tensor(my_arr)

In [59]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
my_arr[0]

0

In [61]:
my_arr[0] = 99

In [62]:
my_arr

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [63]:
new_arr = np.array([1, 2, 3])

In [64]:
torch.tensor

<function torch._VariableFunctionsClass.tensor>

In [65]:
torch.Tensor

torch.Tensor

In [66]:
torch.tensor(new_arr)

tensor([1, 2, 3])

In [68]:
my_tensor = torch.Tensor(new_arr)

In [69]:
my_tensor.dtype

torch.float32

In [70]:
torch.empty(2, 2)

tensor([[-2.1412e-18,  4.4927e-41],
        [-3.6986e-22,  3.1068e-41]])

In [72]:
torch.empty(4, 2)

tensor([[-2.1412e-18,  4.4927e-41],
        [-3.6654e-22,  3.1068e-41],
        [ 4.4842e-44,  0.0000e+00],
        [ 1.7937e-43,  0.0000e+00]])

In [74]:
torch.zeros(4, 2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [75]:
torch.zeros(4, 3, dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [76]:
torch.zeros(4, 4, dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [78]:
torch.arange(0, 18, 2).reshape(3, 3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [80]:
torch.linspace(0, 18, 12).reshape(3, 4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [81]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [82]:
my_tensor = torch.tensor([1, 2, 3])

In [83]:
my_tensor.dtype

torch.int64

In [85]:
my_tensor.type()

'torch.LongTensor'

In [86]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [88]:
my_tensor.dtype

torch.int64

In [89]:
torch.rand(4, 3)

tensor([[0.1448, 0.8216, 0.1449],
        [0.0869, 0.0469, 0.3682],
        [0.2333, 0.4657, 0.4297],
        [0.8035, 0.1262, 0.7817]])

In [90]:
torch.randn(4, 3)

tensor([[ 1.7996, -0.3897, -1.2345],
        [-0.4793,  1.9929, -0.9269],
        [-2.2624, -1.7099,  0.4393],
        [-0.5647, -0.2462,  0.6122]])

In [93]:
torch.randint(low=0, high=11, size=(5, 5, 5))

tensor([[[ 1,  5,  4,  2, 10],
         [ 7, 10,  3,  0,  5],
         [ 0,  3, 10,  7,  2],
         [10,  0,  6,  1,  0],
         [ 7,  1,  3,  2,  8]],

        [[ 0,  4,  4,  5,  7],
         [ 7,  3,  4,  6,  5],
         [ 6,  5,  1,  0,  9],
         [ 8,  5,  7, 10,  0],
         [ 8,  1,  9,  2,  1]],

        [[ 0,  1,  4,  9,  8],
         [ 2,  6,  2,  7,  5],
         [10, 10,  7,  3,  6],
         [ 9,  4,  9,  7, 10],
         [ 4,  2,  6,  8,  2]],

        [[ 0,  9,  8,  0,  2],
         [ 2,  7, 10,  5,  5],
         [ 0,  6,  9,  0,  4],
         [ 5,  5, 10,  6,  9],
         [ 9,  5,  0,  2,  7]],

        [[ 0,  0,  5,  8,  7],
         [10,  5, 10,  7,  5],
         [ 5,  0,  4,  0,  6],
         [ 8,  7,  9,  4,  0],
         [ 9,  5,  1, 10,  9]]])

In [94]:
x = torch.zeros(2, 5)

In [95]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [96]:
x.shape

torch.Size([2, 5])

In [97]:
torch.rand_like(x)

tensor([[0.9896, 0.8524, 0.0410, 0.8927, 0.2844],
        [0.1205, 0.5412, 0.1893, 0.5416, 0.7983]])

In [98]:
torch.randn_like(x)

tensor([[-1.1339, -1.6659, -0.2428,  0.3303,  0.6764],
        [-1.4231, -0.7967, -0.5684,  0.2916, -1.1368]])

In [99]:
torch.randint_like(x, low = 0, high = 11)

tensor([[ 2.,  6.,  2.,  3.,  9.],
        [10., 10.,  6.,  9.,  7.]])

In [106]:
torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [107]:
torch.rand(2, 3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [108]:
torch.rand(2, 3)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

In [109]:
import torch
import numpy as np

In [110]:
x = torch.arange(6).reshape(3, 2)

In [111]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [112]:
x[2]

tensor([4, 5])

In [117]:
x[0, 1]

tensor(1)

In [118]:
x[:,1]

tensor([1, 3, 5])

In [119]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [120]:
x = torch.arange(10)

In [121]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [124]:
x.view(5, 2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [125]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
x = torch.arange(10)

In [127]:
x.shape

torch.Size([10])

In [133]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [134]:
x[0] = 999

In [135]:
x

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [138]:
z = x.view(2, 5)

In [139]:
z

tensor([[999,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [140]:
x = torch.arange(10)

In [141]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
x.shape

torch.Size([10])

In [144]:
z.view(2, -1)

tensor([[999,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [146]:
x.view(-1, 2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [147]:
a = torch.tensor([1, 2, 3])

In [148]:
b = torch.tensor([5, 6, 7])

In [149]:
a + b

tensor([ 6,  8, 10])

In [150]:
torch.add(a, b)

tensor([ 6,  8, 10])

In [151]:
a = a + b
a

tensor([ 6,  8, 10])

In [152]:
a.mul(b)

tensor([30, 48, 70])

In [153]:
a = a * b
a

tensor([30, 48, 70])

In [154]:
a.mul_(b)

tensor([150, 288, 490])

In [155]:
a = torch.tensor([1., 2., 3.])

In [156]:
b = torch.tensor([2., 3., 5.])

In [157]:
a * b

tensor([ 2.,  6., 15.])

In [158]:
a = torch.tensor([[0, 2, 4], [1, 3, 5]])

In [159]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [160]:
b = torch.tensor([[6, 7], [8, 9], [10, 11]])

In [161]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [162]:
a.shape

torch.Size([2, 3])

In [163]:
b.shape

torch.Size([3, 2])

In [164]:
torch.mm(a, b)

tensor([[56, 62],
        [80, 89]])

In [165]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [168]:
x = torch.tensor([2.0, 3.0, 4.0, 5.])

In [169]:
x.norm()

tensor(7.3485)

In [170]:
x.numel()

4

In [172]:
len(x)

4

In [174]:
import torch
import numpy as np


In [175]:
np.random.seed(42)
torch.manual_seed(42)

In [176]:
arr = np.random.randint(0, 5, 6)

In [177]:
arr

array([3, 4, 2, 4, 4, 1])

In [178]:
x = torch.from_numpy(arr)

In [179]:
x = x.type(torch.int64)

In [181]:
x.type()

'torch.LongTensor'

In [182]:
x = x.reshape(3, 2)

In [183]:
x

tensor([[3, 4],
        [2, 4],
        [4, 1]])

In [184]:
x[:, 1]

tensor([4, 4, 1])

In [185]:
x ** 2

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [186]:
x * x

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [188]:
y = torch.randint(0, 5, (2, 3))

In [189]:
y

tensor([[2, 2, 1],
        [4, 1, 0]])

In [190]:
x.mm(y)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])